# Generated by Django 5.0.3 on 2024-03-26 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=20000)),
                ('code_path', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(verbose_name='date published')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_generator.technology')),
            ],
        ),
    ]
