# Generated by Django 5.0.3 on 2024-04-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
