# Generated by Django 5.0.3 on 2024-04-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='processed_specs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
