# Generated by Django 5.0.3 on 2024-04-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0002_alter_software_processed_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='llm_assistant_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='llm_thread_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
