# Generated by Django 5.0.3 on 2024-05-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0004_software_generation_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='instructions',
            field=models.CharField(max_length=72, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='github_repo_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
