# Generated by Django 5.0.3 on 2024-05-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0006_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='current_deployment_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='vercel_project_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
