# Generated by Django 5.0.3 on 2024-05-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0008_remove_software_current_deployment_id_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='vercel_repoId',
            field=models.IntegerField(null=True),
        ),
    ]
