# Generated by Django 5.0.3 on 2024-05-30 23:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0009_deployment_vercel_repoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deployment',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
