# Generated by Django 5.0.3 on 2024-07-31 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0010_deployment_created_at_deployment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM_Run_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='gpt-3.5-turbo-0125', max_length=255)),
                ('time_elapsed', models.DurationField(null=True)),
                ('run_number', models.IntegerField(default=1)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_runs', to='code_generator.software')),
            ],
        ),
    ]
