# Generated by Django 5.0.3 on 2024-08-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0011_llm_run_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm_run_stats',
            name='manual_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
