# Generated by Django 5.0.3 on 2024-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0012_llm_run_stats_manual_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm_run_stats',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
