# Generated by Django 5.0.3 on 2024-08-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0013_llm_run_stats_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm_run_stats',
            name='specs_proc_run',
            field=models.BooleanField(default=False),
        ),
    ]
