# Generated by Django 5.0.3 on 2024-08-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_generator', '0014_llm_run_stats_specs_proc_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_run_version_change',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='llm_run_stats',
            name='model',
            field=models.CharField(default='gpt-4o-mini', max_length=255),
        ),
    ]
